In [1]:
import pandas as pd

df = pd.read_csv("quikr_car.csv")

# Display first 5 rows
print(df.head())

                                     name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000

   kms_driven fuel_type
0  45,000 kms    Petrol
1      40 kms    Diesel
2  22,000 kms    Petrol
3  28,000 kms    Petrol
4  36,000 kms    Diesel

In [2]:
print(df.shape)

(892, 6)

In [3]:
import pandas as pd
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB
None

In [4]:
print(df.isnull().sum())

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [5]:
print(df.describe())

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [6]:
df=df[df['Price']!='Ask For Price']

In [7]:
df['Price'] = df['Price'].str.replace(',', '').astype(int)

In [8]:
print(df['Price'])

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
887    310000
888    260000
889    390000
890    180000
891    160000
Name: Price, Length: 857, dtype: int32

In [9]:
print(df['kms_driven'].unique())

['45,000 kms' '40 kms' '28,000 kms' '36,000 kms' '41,000 kms' '25,000 kms'
 '24,530 kms' '60,000 kms' '30,000 kms' '32,000 kms' '48,660 kms'
 '4,000 kms' '16,934 kms' '43,000 kms' '35,550 kms' '39,522 kms'
 '39,000 kms' '55,000 kms' '72,000 kms' '15,975 kms' '70,000 kms'
 '23,452 kms' '35,522 kms' '48,508 kms' '15,487 kms' '82,000 kms'
 '20,000 kms' '68,000 kms' '38,000 kms' '27,000 kms' '33,000 kms'
 '46,000 kms' '16,000 kms' '47,000 kms' '35,000 kms' '30,874 kms'
 '15,000 kms' '29,685 kms' '1,30,000 kms' '19,000 kms' '54,000 kms'
 '13,000 kms' '38,200 kms' '22,000 kms' '50,000 kms' '13,500 kms'
 '3,600 kms' '45,863 kms' '60,500 kms' '12,500 kms' '18,000 kms'
 '13,349 kms' '29,000 kms' '44,000 kms' '42,000 kms' '14,000 kms'
 '49,000 kms' '36,200 kms' '51,000 kms' '1,04,000 kms' '33,333 kms'
 '33,600 kms' '5,600 kms' '7,500 kms' '26,000 kms' '24,330 kms'
 '65,480 kms' '2,00,000 kms' '59,000 kms' '99,000 kms' '2,800 kms'
 '21,000 kms' '11,000 kms' '66,000 kms' '3,000 kms' '7,000 kms'
 '38,500 kms' '37,200 kms' '43,200 kms' '24,800 kms' '45,872 kms'
 '40,000 kms' '11,400 kms' '97,200 kms' '52,000 kms' '31,000 kms'
 '1,75,430 kms' '37,000 kms' '65,000 kms' '3,350 kms' nan '75,000 kms'
 '62,000 kms' '73,000 kms' '2,200 kms' '54,870 kms' '34,580 kms'
 '97,000 kms' '60 kms' '80,200 kms' '3,200 kms' '0,000 kms' '5,000 kms'
 '588 kms' '71,200 kms' '1,75,400 kms' '9,300 kms' '56,758 kms'
 '10,000 kms' '56,450 kms' '56,000 kms' '32,700 kms' '9,000 kms' '73 kms'
 '1,60,000 kms' '58,559 kms' '57,000 kms' '1,70,000 kms' '80,000 kms'
 '6,821 kms' '23,000 kms' '34,000 kms' '1,800 kms' '4,00,000 kms'
 '48,000 kms' '90,000 kms' '12,000 kms' '69,900 kms' '1,66,000 kms'
 '122 kms' '0 kms' '36,469 kms' '7,800 kms' '24,695 kms' '15,141 kms'
 '59,910 kms' '1,00,000 kms' '4,500 kms' '1,29,000 kms' '300 kms'
 '1,31,000 kms' '1,11,111 kms' '59,466 kms' '25,500 kms' '44,005 kms'
 '2,110 kms' '43,222 kms' '1,00,200 kms' '65 kms' '1,40,000 kms'
 '1,03,553 kms' '58,000 kms' '1,20,000 kms' '49,800 kms' '100 kms'
 '81,876 kms' '6,020 kms' '55,700 kms' '18,500 kms' '53,000 kms'
 '35,500 kms' '22,134 kms' '1,000 kms' '8,500 kms' '87,000 kms'
 '6,000 kms' '8,000 kms' '55,800 kms' '56,400 kms' '72,160 kms'
 '11,500 kms' '1,33,000 kms' '2,000 kms' '88,000 kms' '65,422 kms'
 '1,17,000 kms' '1,50,000 kms' '10,750 kms' '6,800 kms' '9,800 kms'
 '57,923 kms' '30,201 kms' '6,200 kms' '37,518 kms' '24,652 kms' '383 kms'
 '95,000 kms' '3,528 kms' '52,500 kms' '47,900 kms' '52,800 kms'
 '1,95,000 kms' '48,008 kms' '48,247 kms' '9,400 kms' '64,000 kms'
 '2,137 kms' '10,544 kms' '1,47,000 kms' '90,001 kms' '48,006 kms'
 '74,000 kms' '85,000 kms' '29,500 kms' '39,700 kms' '67,000 kms'
 '19,336 kms' '60,105 kms' '45,933 kms' '1,02,563 kms' '28,600 kms'
 '41,800 kms' '1,16,000 kms' '42,590 kms' '7,400 kms' '54,500 kms'
 '76,000 kms' '00 kms' '11,523 kms' '38,600 kms' '95,500 kms' '37,458 kms'
 '85,960 kms' '12,516 kms' '30,600 kms' '2,550 kms' '62,500 kms'
 '69,000 kms' '28,400 kms' '68,485 kms' '3,500 kms' '85,455 kms'
 '63,000 kms' '1,600 kms' '77,000 kms' '26,500 kms' '2,875 kms'
 '13,900 kms' '1,500 kms' '2,450 kms' '1,625 kms' '33,400 kms'
 '60,123 kms' '1,37,495 kms' '91,200 kms' '1,46,000 kms' '1,00,800 kms'
 '2,100 kms' '2,500 kms' '1,32,000 kms' 'Petrol']

In [10]:
import pandas as pd

df = pd.read_csv("messy_btech_student_data_50k.csv")

# Display first 5 rows
print(df.head())

     Student Name                  EMAIL Address Age (yrs) Gender   \
0     Priya Mehta     priya.mehta872@example.com      22.0    male
1    Karan Tiwari      karan.tiwari834@gmail.com      21.0  FEMALE
2    Diya Chauhan    diya.chauhan357@outlook.com      19.0     NaN
3     Rahul Yadav     rahul.yadav260@outlook.com      22.0   Other
4  Ishita Chauhan  ishita.chauhan303@example.com      16.0    male

  City/Location Department Name  Course Marks % Annual Salary Phone Number  \
0         Delhi             CSE  M.Tech    84.4       40885.0   9829425658
1       Gurgaon             ECE  M.Tech    90.6       57758.0   9784662806
2        Mumbai             cse    B.Sc    91.4       41814.0   9409801075
3        MUMBAI     Electronics   BTECH    60.0       29242.0   9387127009
4          Pune    Data Science  B.Tech    65.6       61316.0   9680501786

  Admission Date Attendance %  Student_ID
0     2023-01-18         89.7  STU-145078
1     2024-01-06         78.6  STU-136590
2     2022-10-12          NaN  STU-109430
3     2022-01-28         91.3  STU-107096
4     2023-04-09         91.0  STU-120418

In [11]:
df.drop_duplicates(inplace=True)
print(df.shape)
print(df.duplicated().sum())

(50000, 13)
0

In [12]:
print(df.shape)

(50000, 13)

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 50399
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student Name     50000 non-null  object
 1   EMAIL Address    48694 non-null  object
 2   Age (yrs)        49098 non-null  object
 3   Gender           43914 non-null  object
 4   City/Location    48843 non-null  object
 5   Department Name  49093 non-null  object
 6   Course           50000 non-null  object
 7   Marks %          48885 non-null  object
 8   Annual Salary    49000 non-null  object
 9   Phone Number     48498 non-null  object
 10  Admission Date   47993 non-null  object
 11  Attendance %     49244 non-null  object
 12  Student_ID       50000 non-null  object
dtypes: object(13)
memory usage: 5.3+ MB
None

In [15]:
print(df.columns.tolist())

['Student Name', 'EMAIL Address', 'Age (yrs)', 'Gender ', 'City/Location', 'Department Name', 'Course', 'Marks %', 'Annual Salary', 'Phone Number', 'Admission Date', 'Attendance %', 'Student_ID']

In [17]:
df.describe(include='all').T

                 count unique           top  freq
Student Name     50000    959  Ishita Patel   185
EMAIL Address    48694  46871  not-an-email   485
Age (yrs)        49098     21          21.0  7765
Gender           43914     11       unknown  4739
City/Location    48843     21     Bengaluru  2653
Department Name  49093     13            ME  4584
Course           50000      7         BTECH  7220
Marks %          48885    798         100.0  1027
Annual Salary    49000  31444       unknown   167
Phone Number     48498  47507         12345   513
Admission Date   47993   1208    2023-07-15   798
Attendance %     49244    676         100.0  2775
Student_ID       50000  50000    STU-145078     1

In [18]:
df.describe()

,Student Name,EMAIL Address,Age (yrs),Gender,City/Location,Department Name,Course,Marks %,Annual Salary,Phone Number,Admission Date,Attendance %,Student_ID
count,50000,48694,49098,43914,48843,49093,50000,48885,49000,48498,47993,49244,50000
unique,959,46871,21,11,21,13,7,798,31444,47507,1208,676,50000
top,Ishita Patel,not-an-email,21.0,unknown,Bengaluru,ME,BTECH,100.0,unknown,12345,2023-07-15,100.0,STU-145078
freq,185,485,7765,4739,2653,4584,7220,1027,167,513,798,2775,1

In [ ]:
df.rename(columns={
    "Student Name": "student_Name",
    "EMAIL Address": "email",
    "Age (yrs)": "age",
    "Gender": "gender",
    "City/Location": "city",
    "Department Name": "department",
    "Course": "course",
    "Marks %": "marks",
    "Annual Salary": "salary",
    "Phone Number": "phone",
    "Admission Date": "admission_date",
    "Attendance %": "attendance",
    "Student_ID": "student_id"
}, inplace=True)

df.columns

Index(['student_Name', 'email', 'age', 'Gender ', 'city', 'department',
       'course', 'marks', 'salary', 'phone', 'admission_date', 'attendance',
       'student_id'],
      dtype='object')

In [25]:
missing_count = df.isna().sum()
missing_percent = (df.isna().mean() *100).round(2)

missing_report = pd.DataFrame({
    'missing_count': missing_count,
    'missing_percent': missing_percent
}).sort_values(by='missing_percent', ascending=False)
missing_report

                missing_count  missing_percent
Gender                   6086            12.17
admission_date           2007             4.01
phone                    1502             3.00
email                    1306             2.61
city                     1157             2.31
marks                    1115             2.23
salary                   1000             2.00
department                907             1.81
age                       902             1.80
attendance                756             1.51
student_Name                0             0.00
course                      0             0.00
student_id                  0             0.00

In [29]:
import numpy as np

missing_tokens = ["", "NA", "null", "Not Available", "unknown"]

df = df.replace(missing_tokens, np.nan)

print("Total missing values:", df.isna().sum().sum())

df.isna().sum().sort_values(ascending=False)

Total missing values: 25002

Gender            11096
admission_date     2436
phone              1982
email              1747
city               1511
marks              1501
salary             1302
age                1210
department         1205
attendance         1012
student_Name          0
course                0
student_id            0
dtype: int64

In [31]:
# Convert numric columns to numeric data type
df['age']=pd.to_numeric(df['age'],errors='coerce')
df['marks']=pd.to_numeric(df['marks'],errors='coerce')
df['attendance']=pd.to_numeric(df['attendance'],errors='coerce')
df['salary']=pd.to_numeric(df['salary'],errors='coerce')

In [34]:
df.columns

Index(['student_Name', 'email', 'age', 'Gender ', 'city', 'department',
       'course', 'marks', 'salary', 'phone', 'admission_date', 'attendance',
       'student_id'],
      dtype='object')

In [35]:
for col in ["Gender ", "city", "department", "course"]:
    df[col] = df[col].fillna("Unknown")

df["age"] = df["age"].fillna(df["age"].median())

df["salary"] = df["salary"].fillna(df["salary"].median())

df["marks"] = df["marks"].fillna(df["marks"].median())

df["attendance"] = df["attendance"].fillna(df["attendance"].median())

In [36]:
df.describe()

                age         marks        salary    attendance
count  50000.000000  50000.000000  5.000000e+04  50000.000000
mean      20.727280     67.887216  6.937161e+04     77.640834
std        5.108227     16.843138  5.169514e+05     13.171560
min       -5.000000    -10.000000 -5.000000e+03     30.000000
25%       19.000000     57.400000  3.181900e+04     68.800000
50%       21.000000     67.900000  4.010100e+04     78.000000
75%       22.000000     78.500000  5.075800e+04     87.100000
max       99.000000    150.000000  9.999999e+06    100.000000

In [37]:
df['city'].unique()

array(['Delhi', 'Gurgaon', 'Mumbai', 'MUMBAI', 'Pune', 'Chennai', 'Noida',
       'Bengaluru ', 'Jaipur', 'Unknown', 'Indore', 'Bangalore',
       'Hyderabad', 'Gwalior', 'Bengaluru', 'Gurugram', 'Kolkata',
       '  Delhi', 'Lucknow', 'pune '], dtype=object)

In [42]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

text_columns = ["student_Name", "email", "Gender", "city", "department", "course"]

# Strip whitespace from text columns
for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

# Convert selected categorical columns to lowercase
for col in ["Gender", "city", "department", "course"]:
    df[col] = df[col].str.lower()

# Display first 11 rows
display(df[["student_Name", "Gender", "city", "department", "course"]].head(11))

      student_Name   Gender       city    department  course
0      Priya Mehta     male      delhi           cse  m.tech
1     Karan Tiwari   female    gurgaon           ece  m.tech
2     Diya Chauhan  unknown     mumbai           cse    b.sc
3      Rahul Yadav    other     mumbai   electronics   btech
4   Ishita Chauhan     male       pune  data science  b.tech
5       Pooja Jain     male       pune   electronics  m.tech
6      Rahul Kumar     male    chennai           ece  b.tech
7      Kavya Singh    other     mumbai            me  b.tech
8   KAVYA MALHOTRA  unknown     mumbai            it  m.tech
9      Rohan Gupta     male      noida           ece     bca
10     Pooja Yadav     male  bengaluru           cse  b.tech

In [43]:
df.drop_duplicates(inplace=True)
print("Duplicates:",df.duplicated().sum())

Duplicates: 0

In [44]:
print("New Shape:",df.shape)
print("Duplicates remaining:",df.duplicated().sum())

New Shape: (50000, 13)
Duplicates remaining: 0

In [45]:
numeric_cols = ['age','marks','salary','attendance']
for col in numeric_cols:
  df[col] = pd.to_numeric(df[col],errors='coerce')

print(df[numeric_cols].describe())

                age         marks        salary    attendance
count  50000.000000  50000.000000  5.000000e+04  50000.000000
mean      20.727280     67.887216  6.937161e+04     77.640834
std        5.108227     16.843138  5.169514e+05     13.171560
min       -5.000000    -10.000000 -5.000000e+03     30.000000
25%       19.000000     57.400000  3.181900e+04     68.800000
50%       21.000000     67.900000  4.010100e+04     78.000000
75%       22.000000     78.500000  5.075800e+04     87.100000
max       99.000000    150.000000  9.999999e+06    100.000000

In [46]:
#Triner soln : Convert inpossible values to NAn
df.loc[~df['age'].between(17,35),'age'] = np.nan
df.loc[~df['marks'].between(0,100),'marks'] = np.nan
df.loc[df['salary'] <=0,'salary'] = np.nan
df.loc[~df['attendance'].between(0,100),'attendance'] = np.nan

# Refill values after invalid records were converted to nan
df['age'] = df['age'].fillna(df['age'].median())
df['marks'] = df['marks'].fillna(df['marks'].median())
df['salary'] = df['salary'].fillna(df['salary'].median())
df['attendance'] = df['attendance'].fillna(df['attendance'].median())

In [48]:
# Clean email
df["email"] = df["email"].astype("string").str.strip().str.lower()

# Find invalid emails
invalid_emails = ~df["email"].str.match(
    r"^[^\s@]+@[^\s@]+\.[^\s@]+$", na=False
)

print("Invalid emails found:", invalid_emails.sum())

# Replace invalid emails with NaN
df.loc[invalid_emails, "email"] = np.nan


# Clean phone numbers
df["phone"] = (
    df["phone"]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
)

# Find invalid phone numbers
invalid_phone = ~df["phone"].str.match(
    r"^[6-9]\d{9}$", na=False
)

print("Invalid phone numbers found:", invalid_phone.sum())

# Replace invalid phone numbers with NaN
df.loc[invalid_phone, "phone"] = np.nan

Invalid emails found: 3410
Invalid phone numbers found: 2495

In [49]:
df["admission_date"] = pd.to_datetime(df["admission_date"], errors="coerce",dayfirst=True)
print("Missing/invalid admission dates:", df["admission_date"].isna().sum())
print(df["admission_date"].head(10))

Missing/invalid admission dates: 6093
0   2023-01-18
1   2024-01-06
2   2022-10-12
3   2022-01-28
4   2023-04-09
5   2022-02-09
6   2023-10-07
7   2024-10-21
8   2024-11-01
9   2022-02-19
Name: admission_date, dtype: datetime64[ns]

C:\Users\shiva\AppData\Local\Temp\ipykernel_22324\1691733160.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["admission_date"] = pd.to_datetime(df["admission_date"], errors="coerce",dayfirst=True)

In [51]:
final_copy=df.copy()
final_copy.to_csv("this_is_final_and_clean.csv", index=False)
final_copy.head()

,student_Name,email,age,Gender,city,department,course,marks,salary,phone,admission_date,attendance,student_id
0,Priya Mehta,priya.mehta872@example.com,22.0,male,delhi,cse,m.tech,84.4,40885.0,9829425658,2023-01-18,89.7,STU-145078
1,Karan Tiwari,karan.tiwari834@gmail.com,21.0,female,gurgaon,ece,m.tech,90.6,57758.0,9784662806,2024-01-06,78.6,STU-136590
2,Diya Chauhan,diya.chauhan357@outlook.com,19.0,unknown,mumbai,cse,b.sc,91.4,41814.0,9409801075,2022-10-12,78.0,STU-109430
3,Rahul Yadav,rahul.yadav260@outlook.com,22.0,other,mumbai,electronics,btech,60.0,29242.0,9387127009,2022-01-28,91.3,STU-107096
4,Ishita Chauhan,ishita.chauhan303@example.com,21.0,male,pune,data science,b.tech,65.6,61316.0,9680501786,2023-04-09,91.0,STU-120418